---
- name: Check if projects tools/test-setup.sh exists.
  stat:
    path: "{{ zuul_workspace_root }}/src/{{ zuul.project }}/tools/test-setup.sh"
  register: p

- name: Run tools/test-setup.sh.
  shell: tools/test-setup.sh
  args:
    chdir: "{{ zuul_workspace_root }}/src/{{ zuul.project }}"
  when:
    - p.stat.exists
    - p.stat.executable
